# Copyright (C) 2026 meta-magic_mount-rs developers
# SPDX-License-Identifier: GPL-v3

name: ci-build
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "Cargo.*"
      - "module/**"
      - "webui/**"
      - "xtask/**"
      - "tests/**"
      - "build.rs"
      - ".github/workflows/ci.yml"
      - ".github/bot/**"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "Cargo.*"
      - "module/**"
      - "webui/**"
      - "xtask/**"
      - "tests/**"
      - "build.rs"
      - ".github/workflows/ci.yml"
      - ".github/bot/**"
env:
  CARGO_TERM_COLOR: always

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: arm64
            rust-target: aarch64-linux-android
          - target: armv7
            rust-target: armv7-linux-androideabi
          - target: x86-64
            rust-target: x86_64-linux-android
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29
          add-to-path: true
          local-cache: true
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2026-08-22
          targets: ${{ matrix.rust-target }}
          components: rust-src, rustc-codegen-cranelift-preview
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.10
        with:
          run_install: false
          package_json_file: webui/package.json
      - name: Setup node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "lts/*"
          cache: pnpm
          cache-dependency-path: webui/pnpm-lock.yaml
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: android-${{ matrix.rust-target }}
          cache-workspace-crates: "true"
          cache-all-crates: "true"
          save-if: ${{ github.event_name != 'pull_request' }}
      - name: Install cargo-ndk
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk
      - name: Setup Webui deps
        working-directory: webui
        run: pnpm install --frozen-lockfile
      - name: Build
        run: cargo xtask build -t ${{ matrix.target }}
      - name: Upload build output
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: output/*.zip
          if-no-files-found: error

  publish:
    name: Collect artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Download build outputs
        uses: actions/download-artifact@v8
        with:
          pattern: magic_mount_rs-*
          path: output
          merge-multiple: true
          skip-decompress: true
      - name: Upload release version
        uses: actions/upload-artifact@v7
        with:
          name: meta-mm-${{ github.run_number }}
          path: output/*.zip
          if-no-files-found: error
      - name: Upload
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          RUN_NO: ${{ github.run_number }}
          RUN_ID: ${{ github.run_id }}
        run: |
          if [ -z "${BOT_TOKEN:-}" ] || [ -z "${CHAT_ID:-}" ]; then
            exit 0
          fi
          cd .github/bot
          pip3 install -e .
          cd ../..
          python3 -m bot
